### ISSUE TITLE
Remove jquery dependency?

### ISSUE THREAD

**Issue by lokebharti** [BorisMoore/jsviews#115]
If jsRender is jQuery independent, I believe jsviews could follow the trend, because jQuery is getting bloated especially because the era of pre-rendered untracked DOM manipulation is fading away, and soon we would not have a node that is not rendered by an application. Thus all the bells and whistles for DOM manipulation would be extraneous.

**Comment by BorisMoore** [comment]
Closing "After V1.0" issues for now - to reopen as appropriate.

**Comment by sourcebits-kirthanasg** [comment]
Hi..Is there any update on the same ??

**Comment by BorisMoore** [comment]
It is not so much the DOM manipulation that JsViews relies on, but more importantly, the eventing infrastructure. Observable events are implemented as jQuery events, so they expose the jQuery event object etc. 

Making a change would therefore be a major rewrite, and be significantly breaking... No plans for that in the foreseeable future... At best it would a V2.0 a long way down the road...
