### ISSUE TITLE
Support asynchronous module loading

### ISSUE THREAD

**Issue by crimar** [BorisMoore/jsviews#119]
AMD as e.g. implemented by RequireJS provides an easy way to modularize code and manage dependencies. While RequireJS supports loading non-AMD libraries to some degree, it would be great if that was explicitly supported by jsviews, jsrender and jquery.observable. (jQuery already supports this in a backwards compatible way, see at the very bottom of http://code.jquery.com/jquery-1.8.2.js)

**Comment by BorisMoore** [comment]
This support was added in commit 64 https://github.com/BorisMoore/jsviews/commit/b1a33ac163489f0cd99fb090c00418923968e126
