### ISSUE TITLE
What is the syntax for data-linking to multiple targets?

### ISSUE THREAD

**Issue by iboware** [BorisMoore/jsviews#136]
I have a select control which updates the Type property in data, and I have a TAG Control which depends on Type and the Value. When I add an extra data link for the disabled attribute of  the select, Type field loses it's observable feature or it does not trigger events in the tag.

Working:

``` html
<select data-link="Type"> ... </select>
{^{CustomField Type Value //}}
```

Not Working:

``` html
<select data-link="Type, disabled{:ID?'disabled':''}"> ... </select>
{^{CustomField Type Value //}}
```

**Comment by chkhanu** [comment]
Two-way binding for computed observables, plus other options:
`<input data-link="{:name():name} placeholder{:placeholder()}" />`
This was not obvious, so here it is.

**Comment by BorisMoore** [comment]
@chkhanu
I'll add an example to the documentation.

Did you mean 

    <input data-link="{:name():} placeholder{:placeholder()}" />

(Or did you intend to include having a convertBack converter called name?)

**Comment by chkhanu** [comment]
It is intended.
The difference is that `{:name():name}` reacts back (two-way), when `{:placeholder()}` is just a one-way binding. Both name and placeholder are computed observables (extend functions).

**Comment by BorisMoore** [comment]
`{:name()}` would be one-way, but `{:name():}` is two-way. `{:name():name}` is two-way but also expecting a converter registered as "name". If it doesn't find a registered converter, then it returns the value without change. If you register a "name" converter to convert to upper case, for example, then your code will convert the name value to upper case...

**Comment by chkhanu** [comment]
Thank you for clarification!
