### ISSUE TITLE
Support for dependency on both arrayChange and propertyChange - as params or depends declarations

### ISSUE THREAD

**Issue by iboware** [BorisMoore/jsviews#158]
Hello,
```html
<ul>
{^{for ~FilterWorkgroupHistory(CurrentWorkgroup,HistoryList) tmpl="HistoryItemTmpl" /}}
</ul>
```
I have a basic template that only lists some data by an helper function which filters array as you can see.
When I set CurrentWorkgroup (a string property) it works very well, but when I refresh HistoryList (an array) it does not trigger the necessary event.

Here is a basic live example (first button changes workgroup, second one refreshes the array)
http://jsfiddle.net/bBeDN/7/

**Comment by BorisMoore** [comment]
Closing "After V1.0" issues for now - to reopen as appropriate.

**Comment by BorisMoore** [comment]
One aspect of this future feature could be to support the syntax `"people**"` - such as `totalAmount.depends = "people**"` which would make the totalAmount depend on any change in the object graph under people. So in effect `observeAll()` would be used internally to trigger updates.

That way you could have a computed `totalAmount()` to solve this example, without having to write the observeAll code. https://jsfiddle.net/BorisMoore/wch601L9/

	$.link(true, "#output3", {people: people, totalAmount: totalAmount});
