### ISSUE TITLE
Provide a Nuget package for both JsViews and JsRender - and perhaps additional CDN delivery on jsdeliver. (CDN on cdnjs is already available)

### ISSUE THREAD

**Issue by BorisMoore** [BorisMoore/jsviews#174]

**Comment by BorisMoore** [comment]
Also publish JsRender and JsViews to webjars, composer - and register in jQuery plugins registry.

And typescript - see #175

**Comment by Jeni4** [comment]
Why not implement automatic update to CDN by use of the release tagging GitHub has via git tags?
A CDN worth considering for a hosted version would be [CDNJS](https://github.com/cdnjs/cdnjs) :wink:

**Comment by BorisMoore** [comment]
From Christoffer H (not showing here for some reason)

Why not implement automatic update to CDN by use of the release tagging GitHub has via git tags?
A CDN worth considering for a hosted version would be CDNJS :wink:

**Comment by BorisMoore** [comment]
JsRender is now available on cdnjs: https://cdnjs.com/libraries/jsrender

JsViews will soon be added too.

I will later look at making available also on jsdeliver.

**Comment by BorisMoore** [comment]
https://www.nuget.org/packages/jsrender.TypeScript.DefinitelyTyped/0.1.6

**Comment by BorisMoore** [comment]
I will look into NuGet deployment. @michael-lang - we could collaborate on that if you are interested, as with [JsRender NuGet deployment](https://github.com/BorisMoore/jsrender/issues/211)...

**Comment by BorisMoore** [comment]
We are not currently planning to implement NuGet or jsdeliver support. We already have support for CDN delivery,  on cdnjs
