### ISSUE TITLE
Questions about custom tags (And View onDispose feature request)

### ISSUE THREAD

**Issue by virajsanghvi** [BorisMoore/jsviews#195]
This might fit better in jsrender, but because that libraries main goal is to render a template into a string, my questions probably don't mean as much. 

Basically, I have two questions:

1. I use jsrender custom tags to instantiate backbone views. It works pretty well, but I rely on the parent view getting removed for destroying the child view. If the child views are in a data-linked for-loop, this causes some problems in terms of data objects living around. Is there anything within tagCtx or anything else where I can bind to an event that tells me when the view is being removed? I know I can create a special jquery event that'll fire something when an element is removed with jquery, but removeChild() is used a few times within jsviews code...

2. Tags appear to require returning a string which then are displayed. If I had an asynchronous process to figure out what to display, are there any known solutions? Basically, I'm thinking I'd just return an empty string, but once my asynchronous process was over, use some reference to the view to update content. Is there a reference I can use within the tag's execution context or tagCtx?

Sorry in advance if this information is listed anywhere. I wasn't able to find it.

Thanks for your help!

**Comment by BorisMoore** [comment]
Closing "After V1.0" issues for now - to reopen as appropriate.
