### ISSUE TITLE
Breeze support

### ISSUE THREAD

**Issue by bzuidgeest** [BorisMoore/jsviews#208]
Has anyone attempted or looked at integration with the new breeze api?

http://www.breezejs.com/home

I found breeze interesting, but I like jsviews and at the moment it only support knockout and angular....

Apperently to support other template systems you need to write a new modellibrary plugin like this one for knockout, but that is beyond my capabilities.

https://github.com/IdeaBlade/Breeze/blob/master/Breeze.Client/Scripts/IBlade/b00_breeze.modelLibrary.ko.js

**Comment by BorisMoore** [comment]
http://breeze.github.io/doc-js/index.html - "Breeze currently supports AngularJS, Aurelia, Knockout, and BackBone with adapters for other libraries under consideration. We'd be happy to help you write an adapter for a library we don't yet support."

**Comment by BorisMoore** [comment]
Closing "After V1.0" issues for now - to reopen as appropriate.
