### ISSUE TITLE
Improve support for void elements with no self-closing slash, and for upper-case element tag names

### ISSUE THREAD

**Issue by virajsanghvi** [BorisMoore/jsviews#209]
See http://jsfiddle.net/eyKFU/1/

It results in an error: 
Uncaught TypeError: Cannot call method 'indexOf' of null jsviews.js:3100
dataLink jsviews.js:3100
viewLink jsviews.js:3282
refreshTag jsviews.js:3708
(anonymous function) fiddle.jshell.net/eyKFU/1/show/:41

Placing an if (tokens) statement around the use of tokens in that block seems to resolve the error, and I don't see any weirdness on destruction, but I was hoping you could resolve this properly.

I use this same pattern for a ton of other content, but this particular html breaks it.

Interestingly, not using the pass through template for rendering purposes works fine (i.e. just return the html instead of calling this.tagCtx.render();).

**Comment by johan-ohrn** [comment]
Could you fix this also for uppercase html such as:
<span>{{:"apa<BR>bepa"}}</span>

This work:
<span>{{:"apa<br>bepa"}}</span>

Obviously in the real template the ugly html is comming from a database.
using jsviews v0.9.90

**Comment by johan-ohrn** [comment]
Works perfectly. Thanks!

**Comment by BorisMoore** [comment]
This has been fixed in the v1.0.0 release
