### ISSUE TITLE
Datepicker bind minDate issue

### ISSUE THREAD

**Issue by onechock** [BorisMoore/jsviews#224]
Hello

Im trying to use the datepicker from jsviews.com samples. 

Im having  2 datepicker with 2 dates ant trying to bind date from datepicker 1 to minDate in datepicker 2 and it works fine when I change in datepicker 1 the min date on datepicker 2 are set to that date. BUT when I change date in datepicker  2 the date in datepicker 1 are changing to.

ex:

```
{^{datepicker Date1 }} <div></div> {{/datepicker}}

{^{datepicker Date2 
                  ^minDate=Date1
}} <div></div> {{/datepicker}}
```

**Comment by BorisMoore** [comment]
I believe this has been fixed.  http://jsfiddle.net/onechock/n3PPL/12/ appears to work correctly.
