### ISSUE TITLE
observeAll doesn't trigger events on some array changes view setProperty.

### ISSUE THREAD

**Issue by virajsanghvi** [BorisMoore/jsviews#252]
This isn't a huge deal to me as this isn't normal usage, but this surfaced as I was writing tests around some logic that I use to wrap jsviews.

If you take a look at http://jsfiddle.net/sAzVU/1/, you'll see that updating the element of a list via setProperty and a path like 'list.0', observeAll() doesn't trigger an event. Oddly, setting something in an object within an array, i.e. 'list.0.subattr', does trigger an event.

Anyways, not sure how much you were expecting to support something like this, but thought I'd point it out.

**Comment by BorisMoore** [comment]
Consider whether this scenario needs to be supported, but only after V1.0 - or V1.1. - otherwise, close as unsupported...

**Comment by BorisMoore** [comment]
Closing "After V1.0" issues for now - to reopen as appropriate.
