### ISSUE TITLE
jsviews seems incompatible with browserify

### ISSUE THREAD

**Issue by badiezadegan** [BorisMoore/jsviews#254]
How can jsviews get compatible with [browserify](http://browserify.org)?

**Comment by BorisMoore** [comment]
@badiezadegan, @gbouthenot: 
With Commit 65, JsViews and JsRender now have built-in support for Browserify. JsRender has a built-in browserify transform for including templates - in the form of server-side html pages - in the client bundle. See https://github.com/BorisMoore/jsrender/blob/master/gulpfile.js#L9 - and in particular this line: https://github.com/BorisMoore/jsrender/blob/master/gulpfile.js#L18 - for usage. 

After running the gulp task, `gulp bundle`, the client bundles are created for this set of unit tests: 
https://github.com/BorisMoore/jsrender/blob/master/test/unit-tests-browserify.html - or here for JsViews: https://github.com/BorisMoore/jsviews/blob/master/test/unit-tests-browserify.html.

**Comment by BorisMoore** [comment]
JsRender and JsViews also have full AMD support, see http://borismoore.github.io/jsviews/test/unit-tests-amd-scriptloader.html.

Keeping this issue open for tracking the upcoming publishing of JsRender and JsViews to NPM (with full Express and Hapi integration) as well as webjars, composer, typescript...

**Comment by BorisMoore** [comment]
JsRender has now been published to NPM and Bower, and includes Browserify support with a transfrom jsrender/tmplify. See https://github.com/BorisMoore/jsrender-node-starter

Keeping this issue open for tracking publishing of JsRender and JsViews to webjars, composer, typescript... - and registering in jQuery plugins registry also...
