### ISSUE TITLE
Dependent Select Lists

### ISSUE THREAD

**Issue by badiezadegan** [BorisMoore/jsviews#266]
I used jsviews to fill three dependent select lists.
http://jsfiddle.net/badiezadegan/2xu3k/
 Although the lists are filled correctly, their data-linked values are not set synchronously. How can I have the last select value to be set just after the first one is selected?
Is it possible to do it without using `$.observable`?

Thanks

**Comment by BorisMoore** [comment]
For V1 there won't be additional support. I'll close this for now. That said, if you have suggestions for a more declarative approach, I'd be interested to see any specific ideas or syntax that you might propose.
