### ISSUE TITLE
Remove item from closest array

### ISSUE THREAD

**Issue by UltCombo** [BorisMoore/jsviews#295]
Hello,

I'm using JsViews to display nested arrays of objects. Each object (top-level or nested) has a remove button which should remove it from the closest parent array. What's the best/correct way to implement this? Please see [this fiddle](http://jsfiddle.net/k41nm9ve/).

The relevant test case code in case jsfiddle goes down:

```html
<div id="foo"></div>
<script id="foo-tpl" type="text/x-jsrender">
{^{for items}}
<div class="parent">
    <h1><button class="remove">x</button> {{:text}}</h1>
    {^{for items}}
    <div class="child">
        <button class="remove">x</button> {{:text}}
    </div>
    {{/for}}
</div>
{{/for}}
</script>
```

```js
var tpl = $.templates('#foo-tpl');
tpl.link('#foo', {
    items: [
        {
            text: 'a',
            items: [
                {
                    text: 'a - a'
                },
                {
                    text: 'a - b'
                }
            ]
        },
        {
            text: 'b',
            items: [
                {
                    text: 'b - a'
                },
                {
                    text: 'b - b'
                },
                {
                    text: 'b - c'
                }
            ]
        }
    ]
}).on('click', '.remove', function() {
    // this works:
    var view = $.view(this);
    $.observable(view.get('array').data).remove(view.getIndex());
    
    // this too:
    // var view = $.view(this).get('item');
    // $.observable(view.parent.data).remove(view.index);
});
```

Both of the approaches above seem to work fine, however I'm not sure which is preferred (or if there is a better approach).
Are `item` views always direct children of `array` views? Will the approach(es) above break under circumstances that I haven't considered (e.g. having intermediate scopes)?

Thanks.

**Comment by BorisMoore** [comment]
view.parent.data could break if you do something that adds an intermediate view, such as 

```html
{^{for items}}
  <div class="child">
    {^{if foo}}
      <button class="remove">x</button> {{:text}}
    {{/if}}    
  </div>
{{/for}}
```

But yes, the `item` view is always child of the `array` view, so the first approach would not break.

Another approach which will not break would be to create a template parameter `arr`, as follows.

```html
<div id="foo"></div>
<script id="foo-tpl" type="text/x-jsrender">
{^{for items ~arr=items}}
<div class="parent">
    <h1><button class="remove">x</button> {{:text}}</h1>
    {^{for items ~arr=items}}
    <div class="child">
        <button class="remove">x</button> {{:text}}
    </div>
    {{/for}}
</div>
{{/for}}
</script>
```

`view.ctx.arr` will be accessible contextually for the nested views, so you always get the value corresponding to the nearest one, looking up the chain of parent views:

```js
...
.on('click', '.remove', function() {
    var view = $.view(this);
    $.observable(view.ctx.arr).remove(view.getIndex());
});
```

**Comment by UltCombo** [comment]
> view.parent.data could break if you do something that adds an intermediate view, such as

Did you consider that `view` in that sample is actually `view = $.view(this).get('item');`? So it looks like it would work as it'd walk up past the `if` view to reach the `item` view which is always child of `array` view.

The context approach is clean and neat, thank you for the help!

**Comment by BorisMoore** [comment]
Oh right - using either get("item") or get("array")  will not break but using view(this).parent... would potentially break. I was thinking one of your versions was stepping up parents directly from view(this).

**Comment by UltCombo** [comment]
Thanks for the info :smile:
