### ISSUE TITLE
Access Element from Helper

### ISSUE THREAD

**Issue by edsilv** [BorisMoore/jsviews#296]
Hi,

I've made a tree control that needs to elide the titles on each branch/leaf.

I've made an `elide` helper:

    $.views.helpers({
        elide: function(text){
            return util.htmlDecode(util.ellipsis(text, 40));
        }
    });

Here's the (simplified) template:

    <li>\
        <a href="#" title="{{>label}}" class="selected">{{:~elide(text)}}</a>\
    </li>\

However, instead of hard-coding the # of chars to 40 in the helper, I want to be able to access the width of the anchor tag's containing li element.

Looking through the scoped `this` in dev tools, I can't seem to find any reference to the containing element..?

**Comment by BorisMoore** [comment]
JsRender rendering does pure string based concatenation, and that happens independently of the DOM. When you use JsViews, you get DOM 'awareness' - but even then, initial rendering of `{{:~elide(text)}}` is happening as string concatenation, prior to insertion in the DOM.

For your scenario, if you need to make a DOM dependency for your calculation, you can use data-link:

```html
<a href="#" title="{{>label}}" class="selected" data-link="~elide(text)"></a>
```

```js
$.views.helpers({
    elide: function(text){
        var anchorElement = this.linkCtx.elem; // The data-linked element
        return util.htmlDecode(util.ellipsis(text, ...));
    }
});
```

BTW you can also include the title using data-link. 
```html
<a href="#" class="selected" data-link="{:~elide(text)} title{:label}"></a>
```

And also you could consider using a converter, rather than a helper (either should work - it's just a different style):

```html
<a href="#" class="selected" data-link="{elide:text} title{:label}"></a>
```

**Comment by edsilv** [comment]
I've changed it to use data-link, but this.linkCtx doesn't appear to be available in the helper... Here's the file in question:

https://github.com/britishlibrary/UniversalViewer/blob/master/src/modules/coreplayer-treeviewleftpanel-module/treeView.ts#L71

**Comment by BorisMoore** [comment]
If you go to  http://www.jsviews.com/#samples/tag-controls/tree/if-binding

go to the Try It tab and replace the treeTemplate content by:

```html
  <li>
    {{if folders && folders.length}}
      <span class="toggle">{^{:expanded ? '-' : '+'}}</span>
    {{else}}
      <span class="spacer">&bull;</span>
    {{/if}}
    {{>name}}
    <a data-link="~foo(name)"></a>
  </li>
  {^{if expanded}}
    <li>
      <ul>
        {{for folders}}
          {^{tree/}}
        {{/for}}
      </ul>
    </li>
  {{/if}}
```

and add to the beginning of the JS content, the following:

```js
$.views.helpers({
	foo: function(val) {
		return val + " " + this.linkCtx.elem.tagName;
	}
});
```

then hit Run Code - it outputs Categories Categories A etc.

Not sure why that is not working for you.

**Comment by BorisMoore** [comment]
Didn't hear back on this, so closing for now.
