### ISSUE TITLE
round brackets eating

### ISSUE THREAD

**Issue by Mytia** [BorisMoore/jsviews#300]
Hi, found little bug: first parenthesis vanishes, example here http://jsfiddle.net/FyQF6/11/
I think somethings goes wrong in parseTokens function.

**Comment by BorisMoore** [comment]
Yes - good catch - thanks for reporting this. I have a fix ready which will be in the next update. Let me know if you need a private copy of the fix...

**Comment by gbouthenot** [comment]
Thank to both of you. jsviews is great !

**Comment by BorisMoore** [comment]
Fixed in commit 64.
