### ISSUE TITLE
Render duplication in {^{for}} tag when using $.observable().insert() since Commit 63 

### ISSUE THREAD

**Issue by ErikvO** [BorisMoore/jsviews#301]
Hi Boris,

I've used JsViews to render a tree, where tree nodes can be moved to other nodes (by dragging/dropping).

Since commit 63 I encounter an issue where an array is improperly rendered: 1 item in the array is rendered twice.

I've created 2 JsFiddles: one working, one broken to illustrate the issue:
[Working (commit 62)](http://jsfiddle.net/t8gbek13/1/)
[Broken (commit 63)](http://jsfiddle.net/t8gbek13/)

It seems to be related to the reordering of the events in the "_trigger" function.

    if (length !== oldLength) {
        $data.triggerHandler(propertyChangeStr, { change: "set", path: "length", value: length, oldValue: oldLength });
    }
    $data.triggerHandler(arrayChangeStr, eventArgs);

When I put the events in the original order, the issue is gone.

Gr,
Erik.

**Comment by BorisMoore** [comment]
Thanks Erik - yes you are right, that is a bug. 

I have reduced it to a minimal repro here http://jsfiddle.net/t8gbek13/2/. In fact the issue arises from wrapping a `{^{for children}}` with an `{^{if children.length}}`.
I will probably revert that change in the next update, since your scenario looks like it will arise more often than the more subtle and complex scenario that that change had been intended to fix.

Boris

**Comment by ErikvO** [comment]
Hi Boris,

Thanks for the quick answer.

FYI: I noticed it only happens with leaf nodes, which lead me to believe that the issue only shows when the collection is empty. This [JsFiddle](http://jsfiddle.net/t8gbek13/3/) shows that this is indeed the case. Maybe this helps in fixing the issue without having to revert the change?

Erik

**Comment by BorisMoore** [comment]
Yes it is only when it starts out empty.

**Comment by BorisMoore** [comment]
OK - i have a fix for this (without reverting) which will be part of the next update. Thanks again...

**Comment by ErikvO** [comment]
Great! Nice to hear you did not have to revert.
Thanks again for your prompt response!

**Comment by BorisMoore** [comment]
Fixed in commit 64
