### ISSUE TITLE
Using $.observable().removeProperty() against undefined object property

### ISSUE THREAD

**Issue by shimooka** [BorisMoore/jsviews#302]
Hi Boris,

I've created JsFiddle : http://jsfiddle.net/shimooka/um5eut9n/
If I use $.observable().removeProperty() against a "not exist" property, that property is rendered even if the data object does not have, and the next time it is not rendered.

Is this collect behavior ?

p.s. Very thanks for your great work !!

**Comment by BorisMoore** [comment]
Sorry, I hadn't realized that I didn't actually reply to this. It is not the correct behavior. Thanks for pointing it out. I have a fix ready which will be in the next update.

**Comment by shimooka** [comment]
Hi Boris !

I've re-created JsFiddle with Commit 64 and it works fine !
http://jsfiddle.net/shimooka/s6p7557s/

**Comment by BorisMoore** [comment]
Great - though that staging site is technically for pretesting. The commit 64 is not officially published yet, and could change... I'll notify here when the official version is out...

**Comment by BorisMoore** [comment]
BTW - for your jsfiddle to work you would be better to use http://borismoore.github.io/jsviews.com-staging/download/jsviews.js (or similiar for jsviews.min.js) as URL. I updated it here: http://jsfiddle.net/s6p7557s/2/

**Comment by shimooka** [comment]
Hi Boris.
Thanks for additional information. I'll test again with the new official version :-)

**Comment by BorisMoore** [comment]
This has been fixed in commit 64

**Comment by shimooka** [comment]
Hi Boris.

I've tested again and  worked fine ! : http://jsfiddle.net/shimooka/um5eut9n/
Thanks for your work :-)

**Comment by BorisMoore** [comment]
Great. Thanks again for calling out this issue. I had never noticed it... :)
