### ISSUE TITLE
Error: No {^{ tags within elem markup (<input )

### ISSUE THREAD

**Issue by benmetheny** [BorisMoore/jsviews#303]
I'm getting this syntax error and it seems to be a bug although I'm not entirely sure I haven't messed something up. It appears to relate to having either and {{include../}} or {{if.../if}} inside an element along with a 'data-link="..."' attribute. My use case is I'm attempting to reuse an 'attributes' template for common element attributes while still using two way data-link for the value. [This jsFiddle reproduces it](https://jsfiddle.net/4u97a0sc/19/).

Furthermore, [this jsFiddle](https://jsfiddle.net/4u97a0sc/25/) works as expected. I still cannot get the {{include.../}} to work but by replacing {{include}} with the content of the template being included and removing the {{if..}} statement it works. If I leave the {{if}} in along with 'data-link' it's broken.

**Comment by BorisMoore** [comment]
Yes, that has not been supported. See related issues:
See also https://github.com/BorisMoore/jsviews/issues/213 and https://github.com/BorisMoore/jsviews/issues/255

But on reflection I have now been able to add support for scenarios like yours, such as: 

`<someElem {{someTag ...}} ... {{/someTag}} ...>`

as long as the JsViews tags within element markup are not data-linked.

There will still be an error thrown if you try to do

`<someElem {^{someTag ...}} ... {{/someTag}} ...>`

or 

`{^{someTag ...}} <someElem  ...>  {{/someTag }}  ... </someElem.`

There is a staging site with the provisional update here:

https://borismoore.github.io/jsviews.com-staging/#download.

Can you test it to see if it works for your scenarios? Thanks!

**Comment by BorisMoore** [comment]
I have added support for this scenario. Your [jsFiddle reproduces it](https://jsfiddle.net/4u97a0sc/19/) now works. I'll close this issue.
