### ISSUE TITLE
cannot use 'data-xxxx' attribute in data-link with commit 64

### ISSUE THREAD

**Issue by shimooka** [BorisMoore/jsviews#306]
Hi Boris !

I've created a sample fiddle : http://jsfiddle.net/shimooka/fdLsjk40/

You will see two text, 'attrs' and 'data'. The 'attrs' text (in p tag) has 'attr-xxxx' attributes but 'data' doesn't have 'data-xxxx' attributes .
I use JsViews with bootstrap modal dialog,  and want to use with 'data-toggle' and 'data-target' attributes.

If with JsViews commit 63, it works well.

Thanks.

**Comment by BorisMoore** [comment]
Thanks for calling this out. I am on vacation, but when I return in about a week's time, I'll look into this.

**Comment by BorisMoore** [comment]
Yes, this is a bug. The fix is simply to remove the two lines:

https://github.com/BorisMoore/jsviews/blob/master/jsviews.js#L3227-L3228.

I'll include that fix in the next update.

**Comment by shimooka** [comment]
Thanks a lot !

**Comment by BorisMoore** [comment]
This has been fixed with Commit 65.

**Comment by shimooka** [comment]
Hi Boris.

I've checked my fiddle again and worked fine !
Thanks your great work :-)
