### ISSUE TITLE
data-link to an array.length is not observed by WebView on Android

### ISSUE THREAD

**Issue by eugene-panferov** [BorisMoore/jsviews#308]
sorry for confusing header, it is hard to formulate in a natural language. hopefully i put enough keywords in it.

the environment is:
LG Nexus 5 / Android 5.1 / WebView + Apache Cordova 5.0 + jsviews (master, downloaded right now)

the observed symptom is:
i do "observably" insert an item into the array, and the DOM object ("data-linked" to this array's length) does not respond. while the DOM object "data-linked" with "for" to the content of the same array responds properly.

the setup is:
<div data-link="visible{:!Games.length}">No games open</div>

// JS on some event does:
$.observable(Games).insert({name:"xyz",rating:"123"});

before the operation Games is empty, and "No games open" is visible.
after the operation it is still visible.

exactly this code snippet is working perfectly for many months on the desktop browsers.

**Comment by BorisMoore** [comment]
It is difficult for me to test this. Can you create a small jsfiddle - or show me the template markup and code for a small example?

Is it still working on the desktop browser, but not on your Android device?

Can you try to simplify the example and debug what is happening on the Android device? Is the javascript raising an exception? Or is this an HTML DOM issue? Either the javascript or the HTML DOM rendering and behavior must be different in the Android/Web View  environment from the desktop browser....

**Comment by eugene-panferov** [comment]
I AM DEEPLY SORRY! i have posted you the exact example and this fucking stupid github has stripped it off completely. I did not notice that until now.

this is why i always prefer normal humane e-mails.

**Comment by eugene-panferov** [comment]
sorry for the late reply, i was waiting for e-mail notification which never occurred.

jsfiddle will not help, because the effect is located inside Cordova environment.
so, i am going to create a minimal Android application that demonstrates the effect and share it with you.

answering your questions:
the same JS code works fine in desktop env. 
when it fails to update DOM no exception is thrown.

**Comment by eugene-panferov** [comment]
I need to apologize once more.
i have finished the example, and in parallel, upgraded everything on my android.
after the upgrade the effect disappeared, and the .length became observable as expected.

**Comment by BorisMoore** [comment]
OK - thanks for checking...
