### ISSUE TITLE
trigger=true doesn't work for contenteditable elements

### ISSUE THREAD

**Issue by markibanez** [BorisMoore/jsviews#310]
Hi Boris,

Thanks for this great framework.

Anyway, I can't seem to make trigger=true work for contenteditable. A sample of my code is as follows:

`<span contenteditable data-link="{:variable trigger=true:}"></span>`

Any guidance is appreciated.

**Comment by BorisMoore** [comment]
It works fine for me:
http://jsfiddle.net/BorisMoore/7vj35vbp/

**Comment by markibanez** [comment]
Yes you're right. It eventually worked for me, must have been a different issue.

Thank you.
