### ISSUE TITLE
Bug - void tag inserted dynamically as markup

### ISSUE THREAD

**Issue by albanul** [BorisMoore/jsviews#312]
Hi Boris,

I'm trying to render markup with img tag inside from string variable.
It works fine with the self-closed tag img, but fails on img tag without selfclosing, although both variants of tag are correct.

Here is the sample: http://jsfiddle.net/y43cs47y/2/

Thanks!

**Comment by BorisMoore** [comment]
Yes, thanks - that is a bug. I have a fix for it which will be in the next commit.

**Comment by albanul** [comment]
Thank you!

**Comment by BorisMoore** [comment]
This has been fixed with commit 65.
