### ISSUE TITLE
~root helper becomes undefined passing contextHelpers to a link call

### ISSUE THREAD

**Issue by MetoooRepo** [BorisMoore/jsviews#315]
Hi Boris,
migrating from commit 63 to commit 68 i noticed a different behaviour when passing context helpers to a link call.

Look at this fiddle: https://jsfiddle.net/0o8gsbjm/2/

In the above example everything works fine, but as soon as i use context helpers in the inner link call ( https://jsfiddle.net/m0kf2nxv/1/ ) it stops working and ~root becomes undefined.

Using an older version of jsviews, the second example works as expected (https://jsfiddle.net/n0wwL3ay/).

Am i missing something?
Regards,
Salvio

**Comment by BorisMoore** [comment]
Hi Salvio,

Thanks for reporting this issue. Yes it's a bug that came with commit 64. I have a fix for it that I will include soon in the next update.

**Comment by BorisMoore** [comment]
@MetoooRepo: Hi Salvio - this has been fixed with commit 69.

Let me know if you continue to have any issues.
