### ISSUE TITLE
Issue in for tag within a table tag

### ISSUE THREAD

**Issue by othmanee** [BorisMoore/jsviews#316]
Hi Mr Boris Moore, thanx a lot for your great Jsrender, it so usefull, rich and simple.
i think i find an issue but i dont know:
where i set a for tag within a table tag the for wont render?

**Comment by BorisMoore** [comment]
Can you create a jsfiddle to show your problem?

**Comment by othmanee** [comment]
Aah no i forgot to set my template in <script> tag, this solve my problem thank a lot for your response.
