### ISSUE TITLE
Is the APIs in beta release stable?

### ISSUE THREAD

**Issue by jagandecapri** [BorisMoore/jsviews#324]
Hi @BorisMoore,

Is the beta release APIs is stable enough for use? Will it go through any **major** breaking
changes in version 1.0?

Thanks.

**Comment by BorisMoore** [comment]
No I don't expect any major breaking changes. It is actually very stable. Current code for JsRender is already a release candidate, and for JsViews it is officially a Beta candidate, but in fact it is close to being an actual V1 release candidate...

**Comment by jagandecapri** [comment]
Thanks @BorisMoore, looking forward to V1. :+1:
