### ISSUE TITLE
Can't get it to work in Microsoft Edge

### ISSUE THREAD

**Issue by markibanez** [BorisMoore/jsviews#325]
Hi @BorisMoore,

Jsviews doesn't seem to work on Microsoft's latest browser Edge. I'm not getting any error messages too, which isn't helpful. What I'm seeing is that linking does append the script template.

Thanks.

**Comment by BorisMoore** [comment]
It is working for me. For example if I run http://www.jsviews.com/ - with all its samples, or if I run the tests suites here http://www.jsviews.com/test/ - they seem to run fine in Edge browser.

Can you load those pages in your Edge browser - or this http://www.jsviews.com/test/unit-tests-all-jsviews.html or samples such as http://www.jsviews.com/#samples/editable/tags. Do they work for you?

**Comment by markibanez** [comment]
Works for me too. It must be something else. I'll investigate more and will let you know if it's something related to jsviews.

**Comment by BorisMoore** [comment]
Closing.

**Comment by markibanez** [comment]
It was an issue with Edge blocking local file system javascript same as with IE.
