### ISSUE TITLE
Two way data binding through string paths

### ISSUE THREAD

**Issue by markibanez** [BorisMoore/jsviews#327]
Hi @BorisMoore,

I was wondering if it was possible to do two-way data binding using string paths.

If we had the following object model:

```javascript
var model = {
   a: { 
      b: 'c.d'
   },
   c: {
      d: 'databound value'
   }
};
```

What I want to achieve is to use `model.a.b` to bind to `c.d`. I admit the logic may look silly, but I plan on using it in conjunction with the `{^{for}}` tag to dynamically bind values.

Thanks.

**Comment by BorisMoore** [comment]
Sorry - I missed replying to this.

Well there are a view ways you can do that, but here is one. (You could replace the eval code by something better and more secure).

```
<script id="myTmpl" type="text/x-jsrender">
  <input data-link="a.b"/>
  {^{atPath a.b}}
    <input data-link="name"/>
  {{/atPath}}
</script>
```

```
<script>
var model = {
  a: { 
    b: 'c.jo'
  },
  c: {
    jo: {name: "Jo"},
    jeff: {name: "Jeff"}
  }
};

$.views.tags({
  atPath: {
  baseTag: "for",
  render: function(val, b, c) {
    return this.base(eval("this.tagCtx.ctx.root." + val));
  }
}

$.templates("#myTmpl").link("#container", model);
```

If you change the input text box from "c.jo" to "c.jeff" you will see the custom "atPath" tag will move its context to "c.jeff" and show the correct name.

**Comment by BorisMoore** [comment]
Another approach would be to use dynamic linking based on expressions - as in the following example: https://github.com/BorisMoore/jsviews/issues/311#issuecomment-143846808
http://jsfiddle.net/BorisMoore/hqy06tm5/

**Comment by markibanez** [comment]
Awesome! Thanks @BorisMoore
