### ISSUE TITLE
data-link problem img-src

### ISSUE THREAD

**Issue by rand99** [BorisMoore/jsviews#332]
Hi,

I have an array with objects (Name and ID)
I want to make a simply image gallery.

and a Template
```html
            <script id="slideImage" type="text/x-jsrender">
                    <div class="swiper-slide">
                        <div class="card">
                            <div class="card-block">
                                <h4 class="card-title">{^{:Name}}</h4>
                                <img class="card-img" data-link="src{'/timgs/t' + :ID + '.jpg' }"  />
```
simply linking it via

```
    template = $.templates("#slideImage");
    template.link(".swiper-wrapper", img_array);
```

I don't get an error, and the img-tag 's src attribute isn't set?
so i don't get the images
Am I missing something?

the rest works fine

**Comment by rand99** [comment]
found the solution!

here it is if somebody stumbles in the same situation
```javascript
    function GetImgUrl(value) {
      return '/timgs/t'+value+'.jpg';
    }
    var myHelpers = {imgurl: GetImgUrl};
    $.views.helpers(myHelpers);
```

and
```html
 <img class="card-img" src="" data-link="src{:~imgurl(ID)}"  />
```

**Comment by BorisMoore** [comment]
The `:` has to precede the whole expression, right after the `{`: `src{:some expression here}`.

So this should also work:

    <img class="card-img" data-link="src{:'/timgs/t' + ID + '.jpg' }"

**Comment by rand99** [comment]
oh , nice. Thx

**Comment by BorisMoore** [comment]
The wrong syntax you had will now trigger an exception with a **_syntax error_** message.
