### ISSUE TITLE
data-link="{on resetData}" syntax ?

### ISSUE THREAD

**Issue by daslicht** [BorisMoore/jsviews#335]
Hi,
I  found this line in the example code:
```
<button class="reset-btn" data-link="{on resetData}">Reset</button>
```
Where do I find more info about defining event handlers like this (eg by using on ?)

**Comment by BorisMoore** [comment]
There are a few features in JsViews that have so far only been documented by samples, not by real documentation topics. I am gradually adding topics, such as recent ones on $.views.settings, error handling, debug mode, full docs on unobserve, etc. 

The `{on ... }` event binding is one still needing to be done, and I hope to get to it soon...

**Comment by BorisMoore** [comment]
Closing this for now...
