### ISSUE TITLE
Gitter Channel for JSViews ?

### ISSUE THREAD

**Issue by daslicht** [BorisMoore/jsviews#336]
Hi,
I think we should open a Gitter Channel for JSViews , what do you think ?

**Comment by BorisMoore** [comment]
Yes, that would probably be a good idea. Right now I'm still heads down completing the docs, but I'll keep this issue open to remind me to create a Gitter Channel sometime soon.

**Comment by daslicht** [comment]
Yeah that would also raise the presence of JSViews imo

**Comment by BorisMoore** [comment]
Not doing this for now...
