### ISSUE TITLE
for/else does not receive ~var defined in tag "for"

### ISSUE THREAD

**Issue by Jean-Pierre** [BorisMoore/jsviews#340]
For me it's a bug.

See http://jsfiddle.net/33v3Lah8/1/

    {{for testData ~foo=foo }}
        ...
    {{else}}
    	  foo: {{:~foo}}
    {{/for}}

**Comment by albanul** [comment]
@Jean-Pierre 
You can use foo property from your rm object directly

{{for testData ~foo=foo }}
    ...
{{else}}
      foo: **{{:foo}}**
{{/for}}

Because testData array is emty there is no need to create new context
and you are still in {{for}} tag level of context and that's why there is no ~foo variable.

**Comment by Jean-Pierre** [comment]
@albanul 
Thanks, that's right, but his is just a test case.

The else statement contains an included template accepting parameter ~foo without parameter at call time.
With your solution you force me to declare ~foo on parent scope if I can't set ~foo in else statement.
But it's work.

**Comment by Paul-Martin** [comment]
Maybe this is what you are trying to do?

{{for testData ~foo=foo }}
...
{{else ~foo=foo}}
foo: {{:foo}}
{{/for}}

.. or ...

{{for testData ~foo=foo }}
...
{{else}}
	{{include tmpl='bar' ~foo=foo /}}
{{/for}}

**Comment by BorisMoore** [comment]
The intended design is that {{else}) tags convert a single block to multiple blocks. They are 'sibling' blocks, and the corresponding views are siblings. 

You can actually write:

```
{{for array1}}
  ... array1 item blocks
{{else array2}}
  ... array2 item blocks (if no array1 items)
{{else}}
  ... no items block (if no array1 or array2 items)
{{/for}}
```

There you have three sibling blocks, with the following view structure:

- top
  -  arrayView
    - itemView
    - ...
  -  arrayView
    - itemView
    - ...
  -  elseView

Setting a contextual parameter applies to that block, not to sibling blocks, so you can write:

```
{{for array1 ~prm1=...}}
  ... array1 item blocks - ~prm1 in scope
{{else array2 ~prm2=... }}
  ... array2 item blocks - ~prm2 in scope
{{else ~prm3=...}}
  ... no items block - ~prm3 in scope
{{/for}}
```

(Similarly you can set properties, such as tmpl=... and the setting will apply just to that block:

```
{{for array1 tmpl=t1}}
{{else array2 tmpl=t2}}
{{else tmpl=t3}}
{{/for}}
```

Relevant docs are here:

http://www.jsviews.com/#views
http://www.jsviews.com/#elsetag
http://www.jsviews.com/#tagsyntax@blocktag (especially section *Block tags with {{else}}*)
http://www.jsviews.com/#contextualparams

I might add to the last one to specifically say that you can add contextual parameters to {{else}} blocks...

**Comment by Jean-Pierre** [comment]
You cannot say better.
Thanks Boris

**Comment by BorisMoore** [comment]
Documentation updated here: http://www.jsviews.com/#contextualparams. Closing this issue...
