### ISSUE TITLE
Full Webpack support

### ISSUE THREAD

**Issue by ViktorHofer** [BorisMoore/jsviews#341]
Hey Boris, thanks for your great work!

One question. Is the webpack support currently at the same level as the browserify support? For browserify there is a transform which can handle file templates and its sub-templates.

Thanks,
Viktor

**Comment by BorisMoore** [comment]
Right now there is no webpack loader for JsRender templates. It should be possible to write one, probably based fairly closely on the existing Browserify Transform implementation. But right now I am unable to work on it - given other priorities for JsViews/JsRender work towards V1.0 release.

Of course if you are interested in contributing, that could be great.  I started looking at relevant links, below:

https://webpack.github.io/docs/webpack-for-browserify-users.html
https://github.com/webpack/transform-loader
https://github.com/emaphp/handlebars-template-loader
https://github.com/pcardune/handlebars-loader

Another option you could look at is to use the webpack transform loader (above) to load the Browserify JsRender transform...

**Comment by BorisMoore** [comment]
Adding an *After V1* label, and closing for now.
