### ISSUE TITLE
Computed max attribute on <input type=range> quirks

### ISSUE THREAD

**Issue by laurensdijkstra** [BorisMoore/jsviews#348]
When using a data-linked computed observable as the max attribute of an input of type range the input stops updating the value attribute observably. 

The first time one starts manipulating the computed observable max value, the range doesn't respond at all. Only after using the input at least once makes it respond to the computed max attribute. However, the value attribute is still not observably changed.

See https://jsfiddle.net/1tpjj1gb/ for a (contrived) example.

**Comment by Paul-Martin** [comment]
If I understand the behavior you want, I believe you simply need to specify two way data-link using this syntax:
`data-link="val max{:~max() :}"`
https://jsfiddle.net/1tpjj1gb/1/

**Comment by laurensdijkstra** [comment]
Hah! Yes indeed that is what I was looking for :) Thank you!
