### ISSUE TITLE
multiselect onload not showing the selected options as selected

### ISSUE THREAD

**Issue by kthanesh** [BorisMoore/jsviews#352]
Hi

In your sample code I see multiselect has selectedItems array. when the page is loaded why is the first multiselect box is not setting the selected option.

Thanks

Thanesh

**Comment by kthanesh** [comment]
I have added one more for loop for tag._optionsTmpl in multiselect.js so that "selected" attribute is set to the option tag. It worked.

**Comment by BorisMoore** [comment]
Hi Thanesh, 

Good catch, thanks for calling this out. I have taken a look, and I think the issues is with the following lines:

https://github.com/BorisMoore/jsviews/blob/master/jsviews.js#L5125-L5126

which should be replaced by:

	if (linkedElem && linkedElem[0]) {
		if (!tag.noVal && !tag._.chging) {

You should not need to change multiselect.js. The selection is set in this line:

https://github.com/BorisMoore/jsviews.com/blob/gh-pages/download/sample-tag-controls/multiselect/multiselect.js#L70

Let me know if this approach does not work for you, or if you see other issues.

Thanks!

Boris

**Comment by kthanesh** [comment]
Worked 

Thank you for a quick reply.

Thanks

Thanesh

**Comment by BorisMoore** [comment]
This has been fixed on release v0.9.83
