### ISSUE TITLE
'onError' breaks 'for' tag with external template and passing parameters

### ISSUE THREAD

**Issue by trueqbit** [BorisMoore/jsviews#354]
I am trying to link a list of items to table-rows. There are two lists for different purposes, but with the exact same data structure, which is why I want to encapsulate markup for an item into an external template.

The list might be absent from the data, that's why I am using an onError handler. This is even more necessary because the list in turn is wrapped inside another optional container [note that the json is actually produced by x2js from xml].

Here is some simplified code to show what I am talking about:

```
var model = {
  persons: {
    /*person: [
      { name: 'name 1' },
    ]*/
  },
};

{^{for model.persons^person ~prefix='td' tmpl='#rowPartial' onError='fallback'/}}

```
The actual problem that occurs is that jsviews outputs 'fallback' instead of rendering the template.

Fixing the data structure, such that the 'persons' container is always present, is a possibility, but I believe this to be a bug in jsviews, because either removing 'onError' or the '~prefix' parameter makes things work again.

Here is a [fiddle](https://jsfiddle.net/mp1zg7L7/3/) showcasing the issue.

**Comment by BorisMoore** [comment]
Thanks for finding this! Yes, it is a bug. 

The fix is very simple. Change line https://github.com/BorisMoore/jsviews/blob/master/jsviews.js#L3620 to

	sourceValue = linkFn(source, view, $sub);

I'll include the fix in the next update.

**Comment by trueqbit** [comment]
Thanks! The fix is working great, both for data-linked tags and elements.

**Comment by BorisMoore** [comment]
Fixed with [commit 84](https://github.com/BorisMoore/jsviews/commit/3ea9d461db1e39909c65bdd6c271675bdaa836ad)
