### ISSUE TITLE
Rendering unlinked data

### ISSUE THREAD

**Issue by in32bit** [BorisMoore/jsviews#355]
Hi Boris,

At [this ](https://jsfiddle.net/in32bit/s718a8wo/2/) template i'm trying to use rowspan by the length of a collection. But when i add a new object i lose the structure.

Do you have a solution? 

Thanks!

**Comment by BorisMoore** [comment]
The way you have it, it is not data-linked to people.length. You need to write:

```
<td style="vertical-align:middle" data-link="rowspan{:~len}">
  ...
</td>
```

**Comment by in32bit** [comment]
Thank you. I will try to stay more linked.. 
Amazing work.
