### ISSUE TITLE
Deferred data-linking with promise or callback for completion

### ISSUE THREAD

**Issue by BorisMoore** [BorisMoore/jsviews#368]
Deferred data-linking as perf optimization.

**Comment by BorisMoore** [comment]
Closing all 'After V1' issues for now. Will reopen when appropriate.

**Comment by renaudham** [comment]
Hi
What is the status on this?
Thanks

**Comment by BorisMoore** [comment]
No plans to work on this in the near future. See https://github.com/BorisMoore/jsviews/issues/421.
