### ISSUE TITLE
The jsView's website can't show something...

### ISSUE THREAD

**Issue by WildDylan** [BorisMoore/jsviews#375]

**Comment by WildDylan** [comment]
<img width="747" alt="qq20170411-190241 2x" src="https://cloud.githubusercontent.com/assets/2519544/24906235/7a9b2f24-1ee9-11e7-9fc1-ffd3cad747ba.png">

**Comment by BorisMoore** [comment]
It works for me. Is it working again now for you? 

It looks like for some reason you were getting a corrupted version of remarkable.min.js from //cdnjs.cloudflare.com/ajax/libs/remarkable/1.6.2/remarkable.min.js...

**Comment by WildDylan** [comment]
Not work.... 😢

**Comment by BorisMoore** [comment]
If you try to load the following page in your browser, does it work?

```
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8">
<script src="//cdnjs.cloudflare.com/ajax/libs/remarkable/1.6.2/remarkable.min.js"></script>
Hello
</body>
</html>
```

**Comment by WildDylan** [comment]
![fd87d3db-f098-4417-934b-dda75256ecb0](https://cloud.githubusercontent.com/assets/2519544/24987745/37dc4a28-2034-11e7-886b-16b564ebb253.png)

not work... 
I'm in china, this is the reason?

**Comment by BorisMoore** [comment]
Yes, I think so. It works for me here in the US, I think there is a problem with  the CDN for that file, in China.

Can you change that test.html to load this version instead: https://cdnjs.cloudflare.com/ajax/libs/remarkable/1.7.1/remarkable.min.js

If that works, I will soon change jsviews.com to use 1.7.1.  

Also, it may make sense to contact [remarkable](https://github.com/jonschlinkert/remarkable) or CDNS about  the issue. See this old issue: [cdnjs.com unavailable from China](https://github.com/cdnjs/cdnjs/issues/1922).

**Comment by WildDylan** [comment]
`https://cdnjs.cloudflare.com/ajax/libs/remarkable/1.7.1/remarkable.min.js` is work for me.

**Comment by BorisMoore** [comment]
Commit 85 uses v 1.7.1 of remarkable.js - so this problem should now be resolved.

**Comment by WildDylan** [comment]
Many thanks. it works.
