### ISSUE TITLE
Provide a sample implementation of using jsViews in conjunction with a web component or custom element

### ISSUE THREAD

**Issue by wforney** [BorisMoore/jsviews#384]
Having a simple way to template a native web component in combination with jsViews or jsRender would be interesting... Just a thought.

**Comment by wforney** [comment]
Having a simple way to template a native web component in combination with jsViews or jsRender would be interesting... Just a thought.

**Comment by BorisMoore** [comment]
Right, could be interesting.

I'll look at that at some point. But probably not before releasing V1.0. 

OTOH if you have any specific suggestions, or if you want to look at creating a sample with a suggested approach (with or without modified JsViews code) then I'd  be very interested to look at what you might come up with...

**Comment by BorisMoore** [comment]
Closing for possible re-opening after V1
