### ISSUE TITLE
helper does not get updated when "nested" linking

### ISSUE THREAD

**Issue by ainglese** [BorisMoore/jsviews#393]
Hi boris, i think i've spot a bug, but i'm not sure if this is a supported scenario; the effect is that the value from an helper does not get updated when re-linking an element, when that element is inside another linked template.

here's a fiddle with a repro for the issue:
https://jsfiddle.net/494vvhj8/ (jsviews v .88)

note that the issue does not seem to happen in version .84, but happens surely in .86 and .88
https://jsfiddle.net/v43oqo77/1/ (jsviews v .84 - UPDATED, had wrong version of jsviews)

maybe something has changed when disposing the linked view or the helper is not getting updated when re-linking..

i've also found a workaround, removing the element i'm linking to and re-adding after linking seems to "solve" the issue.

**Comment by BorisMoore** [comment]
Thanks for calling this out!

Yes, it is a bit of an edge case, but still, ideally I would like to support it, and provide a fix. It is actually rather complex, but I think I have a working fix now. I'll post it here in a day or two.

**Comment by BorisMoore** [comment]
Here is a proposed fix. Let me know if it doesn't fix the problem, or if you see other issues. Thanks!

[jsviews.js.txt](https://github.com/BorisMoore/jsviews/files/1364117/jsviews.js.txt)

**Comment by BorisMoore** [comment]
Ah I found an issue with my fix. Working on it...

**Comment by BorisMoore** [comment]
This has been fixed in commit 89
