### ISSUE TITLE
Pasting issues with JSviews

### ISSUE THREAD

**Issue by Backslider23** [BorisMoore/jsviews#399]
If I have a two-way binding on a text box, and I right-click and choose to paste text into the box, this change will not be reflected in my bound data.

I've also had reports that using Command-V on a mac (as opposed to Ctrl-V on a PC) causes the data to not get saved either.

In both cases, typing a key after doing the paste will cause the data to get saved.  So it is just a matter of jsviews not seeing the change I think.

**Comment by BorisMoore** [comment]
What version of JsViews are you using? It should work since version 0.9.88. 

See: https://github.com/BorisMoore/jsviews/issues/391

**Comment by BorisMoore** [comment]
What version of JsViews are you using. It should work since v0.9.88.

See https://github.com/BorisMoore/jsviews/issues/391

**Comment by Backslider23** [comment]
I had 0.9.87.  Sorry about that.
