### ISSUE TITLE
Set() support?

### ISSUE THREAD

**Issue by diogeneshamilton** [BorisMoore/jsviews#401]
Hey,

Big fan f JSViews, but we're using it specifically to power our feeds, and we want to refresh them and keep the items unique. There are other ways to do this of course (including view Models), but it would be easiest for us if observable had support for Sets in addition to arrays. Is that something you've thought of supporting?

**Comment by BorisMoore** [comment]
It sounds like a good idea to have that support, but my priority is on getting all the documentation out for JsViews and releasing the official V1.0 version. So I am marking this a Postponed for after V1. 

At that point I may be able to consider it. This issue will serve as a reminder. 

Of course if you are able/interested to look at the code and figure out a potential implementation, I'll be glad to consider integrating code contributions in the future...

**Comment by diogeneshamilton** [comment]
Sounds good! Thanks for the response. In the meantime, I implemented compiled view models for our data, however I still had to implement a quick de-duplication method. Maybe after v1.0 I'll see what I can contribute...

**Comment by BorisMoore** [comment]
That works...
