### ISSUE TITLE
input type='checkbox' not working properly in new version

### ISSUE THREAD

**Issue by peter36** [BorisMoore/jsviews#42]
In previous version (before Mar 6 update), I used this syntax to get and set value for checkbox:

```
 <input data-getfrom="checked:Alarm" data-to="Alarm" type="checkbox"/> 
```

If I use the new syntax like this:

```
<input data-link="Alarm" type="checkbox" />
```

If Alarm property is set to true, it doesn't show as checked at the checkbox. However, I can see that in the view model, the property can be updated when user check or uncheck the checkbox.

What should I do for the new version?

**Comment by omprakash-sharma** [comment]
It's working for me with type="selectboxes" instead of type="checkbox".
or using json format

    {
      'type': 'selectboxes',
        'validate': {
          'required': false
        },
        'persistent': true,
        'protected': false,
        'defaultValue': false,
        'key': '',
        'name': 'checkbox',
        'datagridLabel': true,
        'label': '',
        'hideLabel': false,
        'tableView': true,
        'inputType': 'checkbox',
        'input': true,
    }

**Comment by BorisMoore** [comment]
@omprakash-sharma : I don't understand the comment above. Was this some issue you are raising? selectboxes is not a standard HTML input type...

**Comment by BorisMoore** [comment]
Not a problem, but trying to undestand. So you are using jsviews together with form.io? Are you also using Angular or React. Are you using JsViews data-linking, or just JsRender templates?

**Comment by omprakash-sharma** [comment]
Yeah, I was just exploring form.io with Angular.
