### ISSUE TITLE
I see a way to use with jquery-ui, but what about Bootstrap 4 ?

### ISSUE THREAD

**Issue by renaudham** [BorisMoore/jsviews#425]
Hi

Is there any way to use all this with Bootstrap4, and not only Jquery UI?
Because Bootstrap also has a lot of clean CSS and HTML elements, and specific things like Carroussel etc.

**Comment by BorisMoore** [comment]
Yes, indeed it should work well alongside Bootstrap. I don't know Bootstrap (and all available components and plugins) well enough to know whether in some cases there could be a conflict. But for basic scenarios it certainly seems to work very will with JsViews.

For example I tried integrating this page: https://getbootstrap.com/docs/4.3/examples/checkout/ with JsViews, and made the content templated and dynamic, along with data-binding on the fields etc. It worked well, including the Bootstrap validation code...

**Comment by BorisMoore** [comment]
Did you test this out? Should be good...

**Comment by renaudham** [comment]
Great thanks.
I will try in the coming weeks.

Regards

**Comment by johan-ohrn** [comment]
We're using bootstrap 4 in our project without issues. It's just that there are no custom tags to wrap the bootstrap controls like we have for jquery-ui but it's possible to create them.

**Comment by BorisMoore** [comment]
Thanks for the feedback, Johan. I'll close this now.
