### ISSUE TITLE
Checkbox group support

### ISSUE THREAD

**Issue by BorisMoore** [BorisMoore/jsviews#426]
For context, see: https://github.com/BorisMoore/jsrender/issues/350, from @wklau2006

**Comment by hkvstore** [comment]
Thank you for providing support for this.

**Comment by BorisMoore** [comment]
I have an update ready that includes new checkbox group support, including a {{checkboxgroup}} tag (similar to {{radiogroup}}. However I will be travelling for the next three weeks, and unfortunately did not quite have enough time to complete testing and committing the new version (1.0.4). I expect to do so in the first week of July.

Here is my current code you can test (but with the update I will also provide new docs for checkbox groups, so you may want to wait...).

[jsviews1.0.4d.js.txt](https://github.com/BorisMoore/jsviews/files/3263284/jsviews1.0.4d.js.txt)

**Comment by hkvstore** [comment]
Thanks. It works. 

Tested with:
```html
<div id="result"></div>

<script id="tmpl" type="text/x-jsrender">
	{^{checkboxgroup selectedCar}}
	<label><input type="checkbox" value="none"/>
		None</label><br/>
	<label><input type="checkbox" value="volvo"/>
		Volvo</label><br/>
	<label><input type="checkbox" value="ford"/>
		Ford</label><br/>
	{{/checkboxgroup}}

	<span class="spanbox" data-link="selectedCar||'none'"></span>
</script>

<script>
var tmpl = $.templates("#tmpl");
var data = {selectedCar: ["ford","volvo"]};
tmpl.link("#result", data);
</script>
```

**Comment by hkvstore** [comment]
In the upcoming new doc please also advise how to bind events (e.g. "change" event) to radiogroup and checkboxgroup by `{on} data-link binding` or `{^{on}} tag`. Thanks.

**Comment by BorisMoore** [comment]
This feature has been added in  v1.0.4
