### ISSUE TITLE
onUnbind / onDispose not called

### ISSUE THREAD

**Issue by johan-ohrn** [BorisMoore/jsviews#430]
I created a custom ```{{validate}}``` tag. My problem is that onUnbind is never called when it's removed from the DOM. For whatever reason onUnbind is called if you remove the ```{{slider}}``` tag from the template.

Here is a [fiddle](http://jsfiddle.net/896cmLqk/). Run it with the browser console open.

**Comment by BorisMoore** [comment]
Thanks for  calling this out, Johan.

Here is a proposed fix: 

[jsviews1.0.4e.js.txt](https://github.com/BorisMoore/jsviews/files/3365975/jsviews1.0.4e.js.txt)

**Comment by BorisMoore** [comment]
@johan-ohrn: Hi Johan, let me know if this works for you, when you can... I hope to publish the above update soon,  to include this and other fixes. Also if my suggested slider widget update works for you, I will update the jsviews-jqueryui-widgets.js library too, with that update...

**Comment by johan-ohrn** [comment]
Hi,
I won't be able to confirm until after next week. Vacation... Unfortunately I don't have access to my work from home. 
I'll let you know asap when I'm back. 
Cheers!

**Comment by BorisMoore** [comment]
Thanks for letting me know! Enjoy your vacation....

**Comment by johan-ohrn** [comment]
Could you please link this update as separate js files (jsrender, jsobservable, jsviews) ?

**Comment by BorisMoore** [comment]
Here it is: [download.zip](https://github.com/BorisMoore/jsviews/files/3419433/download.zip)

**Comment by johan-ohrn** [comment]
I can confirm that it work - thanks!

**Comment by BorisMoore** [comment]
Fixed in v1.0.4
