### ISSUE TITLE
Get jquery element for {on...

### ISSUE THREAD

**Issue by alnico2001** [BorisMoore/jsviews#436]
Is there any method for getting the jquery element when using `data-link="{on ~myFunction}"`?

```
myFunction(msg, ev, eventArgs) {
     jqElement = $(this); //this of course does not work
     jqElement = ev.target; //not sure if this can be used to get it

     jqElement.parent().find('.something');
}
```
If I put an id on the element, I could pass that to handler, that would work I guess.

I couldn't find anything here https://www.jsviews.com/#link-events

**Comment by BorisMoore** [comment]
`ev.target`, and also `eventArgs.linkCtx.elem` will each return the HTML element.

If you want a jQuery object, you can do `$(ev.target)`. 

See [this paragraph](https://www.jsviews.com/#link-events@signature) where it says:
- *target: the HTML element where the click event occurred*.


Does that cover what you need?

**Comment by alnico2001** [comment]
I did read that paragraph ;-)

My original (and only) test was `$(ev.target).css('color', 'red');` // this does not work 

Now after your response above, I did another test: `$(ev.target).remove();` // this works

It appears that there are limitations?

However, when testing with this `$(eventArgs.linkCtx.elem).css('color', 'red');` // this works

Note: I don't think I would have put this together (eventArgs.linkCtx.elem).  I think I need to start a cheat sheet for myself ;-)

**Comment by BorisMoore** [comment]
`$(ev.target).css('color', 'red');`  works for me.

Also, I would expect `ev.target === eventArgs.linkCtx.elem`. 

Can you provide a sample/jsfiddle where `$(ev.target).css('color', 'red');` does not work?

**Comment by BorisMoore** [comment]
Closing for now, since not a JsViews issue, I think. But please provide a jsfiddle, if `$(ev.target).css('color', 'red');` is not working, and I will reopen.

**Comment by alnico2001** [comment]
Sorry for late response.
Yes it works...I believe I had the function signature parameters/arguments mis-aligned.
Apologies
