### ISSUE TITLE
How to observe property array properly?

### ISSUE THREAD

**Issue by Dissolubilis** [BorisMoore/jsviews#437]
Hello,
How can I observe (or set 'depends' for computed observable) for changing of array items properties?

I.E.
```
{ property : [ 
  {items: [{x:1}]}, 
  {items: [{x:2}]}
] };
```
Now how can I observe only length of all 'items' arrays? `depends = ["**"]` is working, but what exact path for observing such properties? There is JsFiddle with example of what I want to achieve https://jsfiddle.net/rp3khq1z/4/

**Comment by BorisMoore** [comment]
Looks like you figured it out? 

    data.total.depends = "property.[].items.length";
    // or data.total.depends = ["property.[].items.length"];

Right?

**Comment by Dissolubilis** [comment]
Right, thank you. But I've realised it is not the example I wanted to show. I still have some issue in project, when only greedy path "**" is working for observing array properties of object, but I cannot reproduce it alone yet. If I find it, I wll reopen issue
