### ISSUE TITLE
better error message

### ISSUE THREAD

**Issue by johan-ohrn** [BorisMoore/jsviews#438]
This [fiddle](https://jsfiddle.net/9xzyr8ke/)

html: 
```
<div id="ph"></div>
```
js:
```
$.templates("{{:~unknown()}}").link("#ph");
```
gives the following unhelpful error message:
```
Uncaught TypeError: view.ctxPrm(...) is not a function
...
```

I would rather the error message mention the name of the context parameter, in this case "unknown".

It would also be helpful in tracking down the error if the exception would write out which template and tag hierarchy that threw the exception.

**Comment by BorisMoore** [comment]
Thanks for calling this out, Johan. I agree the error message is not ideal, and that the additional information would be helpful, but unfortunately it looks like a fix is difficult to achieve. If it were possible at all it would imply significant changes and additions to the the template parsing code, with corresponding cost in perf, code size, and potentially stability of current code. 

So my current take is that this is a 'won't fix`. 

In fact the parsed code is `view.ctxPrm("unknown")()` and the browser throws an error. For Chrome it is **view.ctxPrm(...) is not a function**. For Safari it is **undefined is not a function**...  It would be nice if the browser gave the message **view.ctxPrm("unknown") is not a function**. But it doesn't, and we have no control over that...

**Comment by johan-ohrn** [comment]
What I'm discovering is that I come back to a month old code or more and change something, perhaps a web api or something in a viewmodel which result in a template all of a sudden being linked against a new data structure. Bang I'm getting this kind of error. At best of times it's easy to find out which template expression is the culprit but it happens all to often that I have to remove a lot of template code and by process of elimination locate the template expression that is causing the error.

That being said could you tag this issue somehow such that if work is done on the template parsing code, this could be looked at as well?

**Comment by johan-ohrn** [comment]
That first option does what I need. Thanks.

**Comment by BorisMoore** [comment]
Closing, since the requested feature is already available through existing feature: https://www.jsviews.com/#onerror@debugmode-function.
