### ISSUE TITLE
Delimiters not working for "[ " and " ]"

### ISSUE THREAD

**Issue by Autoflow** [BorisMoore/jsviews#443]
Hi, after a long search for practical delimiters i found "[ " and " ]" for myself being easy to read.
Now there's a problem with conditional sections. 

This [jsfiddle](https://jsfiddle.net/d6v52u90/1/) says: JsRender Error: Syntax error
Unmatched or missing {{/else}}, in template: [ if checked ] true [ else ] false [ /if ] 

Without whitespaces everything works fine so my question is if this issue can be fixed ?

**Comment by BorisMoore** [comment]
Yes, that will not work. The delimiters must consist of two non-alphanumeric (and non-space) characters. I
I'll update the docs [here](https://www.jsviews.com/#settings/delimiters) to be more specific concerning white space characters.

You can do "[_" and "_]" for example....

**Comment by BorisMoore** [comment]
I'll close this since the behavior is 'by design' - and we won't be able to allow using white-space within delimiters....
