### ISSUE TITLE
jsrender.min.js.map truncated

### ISSUE THREAD

**Issue by Jerry2048** [BorisMoore/jsviews#445]
Somehow jsrender.min.js.map was truncated between v1.0.5 and v1.0.6.  The newer one ends abruptly in the middle of the comment "// Test is satisfied, so render content on current context", causing an improperly formed JSON file and a warning when debugging my website in Chrome with F12: "DevTools failed to load SourceMap: Could not parse content for http://[name of site]/js/jsrender.min.js.map: Unexpected end of JSON input".

**Comment by BorisMoore** [comment]
Thanks for calling this out. I hadn't realized there was a problem. I don't know how it got truncated. I look into it, but meantime you can get a valid jsrender.min.js.map file here:

https://www.jsviews.com/download/jsrender.min.js.map

(also linked from the https://www.jsviews.com/#download page).

Let me know if that version works correctly for you...

**Comment by Jerry2048** [comment]
Thank you, I'll try it when I'm back at work on Monday.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Boris MooreSent: Thursday, April 30, 2020 6:52 PMTo: BorisMoore/jsviewsReply To: BorisMoore/jsviewsCc: Jerry2048; AuthorSubject: Re: [BorisMoore/jsviews] jsrender.min.js.map truncated (#445)
Thanks for calling this out. I hadn't realized there was a problem. I don't know how it got truncated. I look into it, but meantime you can get a valid jsrender.min.js.map file here:
https://www.jsviews.com/download/jsrender.min.js.map
(also linked from the https://www.jsviews.com/#download page).
Let me know if that version works correctly for you...

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/BorisMoore/jsviews/issues/445#issuecomment-622160066",
"url": "https://github.com/BorisMoore/jsviews/issues/445#issuecomment-622160066",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Jerry2048** [comment]
‎Yes, that version works and doesn't cause the warning. Thank you very much!                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Jerry OrlandoSent: Thursday, April 30, 2020 6:56 PMTo: Boris MooreCc: Jerry OrlandoSubject: Re: [BorisMoore/jsviews] jsrender.min.js.map truncated (#445)                                                                                      Thank you, I'll try it when I'm back at work on Monday.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Boris MooreSent: Thursday, April 30, 2020 6:52 PMTo: BorisMoore/jsviewsReply To: BorisMoore/jsviewsCc: Jerry2048; AuthorSubject: Re: [BorisMoore/jsviews] jsrender.min.js.map truncated (#445)
Thanks for calling this out. I hadn't realized there was a problem. I don't know how it got truncated. I look into it, but meantime you can get a valid jsrender.min.js.map file here:
https://www.jsviews.com/download/jsrender.min.js.map
(also linked from the https://www.jsviews.com/#download page).
Let me know if that version works correctly for you...

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/BorisMoore/jsviews/issues/445#issuecomment-622160066",
"url": "https://github.com/BorisMoore/jsviews/issues/445#issuecomment-622160066",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by BorisMoore** [comment]
This has been fixed in new release v1.0.7

**Comment by BorisMoore** [comment]
This truncated .map file has unfortunately [happened again](https://github.com/BorisMoore/jsrender/issues/362#issuecomment-734646833) on v1.0.8. I'll probably need to release a new version (v1.0.9) to fix this on the CDNJS site.

But meantime a valid jsrender.min.js.map file for v1.0.8 is available here:

https://www.jsviews.com/download/jsrender.min.js.map

(also linked from the https://www.jsviews.com/#download page).

**Comment by BorisMoore** [comment]
This has been resolved in v1.0.9
