### ISSUE TITLE
multiselect not updating when linked array changes

### ISSUE THREAD

**Issue by johan-ohrn** [BorisMoore/jsviews#450]
Please have a look at this [fiddle](https://jsfiddle.net/x0eun9yq/). (code below)
Notice that the select element without the copy converter does not update.

I found that the select element does not update it's selected values when you observably modify the selectedValues array.

I followed the code flow and found this line in jquery.views.js:
```623: if (change = change || targetVal !== sourceValue) {```
As a workaround I realized I can just create a converter that copies the array so that targetVal and sourceValue are different array instances.
It works but it's not very obvious.

```
html:
<div id="ph"></div>

js:
$.views.converters({
  copy: function(arr){return arr.slice();}
})

var vm = {
  selectedValues: ["value2"]
};

$.templates("\
	with copy converter \
  <select multiple data-link='{copy:selectedValues:}'>	\
    <option value='value1'>1</option>	\
    <option value='value2'>2</option>	\
  </select>		\
  without copy converter \
  <select multiple data-link='selectedValues'>	\
    <option value='value1'>1</option>	\
    <option value='value2'>2</option>	\
  </select>		\
").link("#ph", vm);


setTimeout(function() {
  console.log("blah")
	$.observable(vm.selectedValues).refresh(["value1"]);
},1000)
```

**Comment by BorisMoore** [comment]
Thanks Johan. I'll look into it...

**Comment by BorisMoore** [comment]
Hi Johan,
It's been a long time and I did in fact find a fix for your issue above, but also discovered some slightly related problems with the checkboxgroup tag. I have been working towards a new update which will include your the fix for your issue. But it's taking a while.... If you can wait for your fix, that's good, but if you would hope to get it sooner, let me know and I'll probably create an intermediate update with just your fix...

**Comment by johan-ohrn** [comment]
Hi,
Good to hear. We will wait for the fix since we have a workaround for the problem.
Thanks

**Comment by BorisMoore** [comment]
This update should fix your issue, along with a number of other small issues I found, particularly concerning `<select>`, `multiselect`, and `{{checkboxgroup}}`, (and some  elsewhere...)

[jsviews8e.zip](https://github.com/BorisMoore/jsviews/files/5387812/jsviews8e.zip)

Let me know if it works for you...
Thanks!

**Comment by BorisMoore** [comment]
Update - I am checking another possible issue, so  probably better to wait before testing jsviews8e, above. I'll keep you posted if there is a corrected version coming...

**Comment by BorisMoore** [comment]
OK, I think this update is good. Let me know if you find any issues in your environment'
Thanks!

[jsviews8f.zip](https://github.com/BorisMoore/jsviews/files/5405565/jsviews8f.zip)

**Comment by BorisMoore** [comment]
I'm moving towards publishing the above a v1.0.8. Of course, if you do find an issue before I actually publish, then I'll put it on hold, but I am pretty sure that for known issues it is good...

**Comment by johan-ohrn** [comment]
I probably won't be able to test it in the coming days. I'm stuck with some major pita I must attend to first. I'll write back here though when I have tried it. I'm sure it will work tho :)

**Comment by BorisMoore** [comment]
Thanks Johan, yes, that's fine. I'll go ahead with what we have. Worst case we'll need a v1.0.9 subsequently. (Which at some point will happen anyway...)
Thanks for letting me know status so rapidly...!

**Comment by BorisMoore** [comment]
Resolved in v1..0.8
