### ISSUE TITLE
Support data-link binding back to a simple array of strings

### ISSUE THREAD

**Issue by bluefox** [BorisMoore/jsviews#53]
JsViews seems to work fine when binding data from a simple array with #data (which basically is a short cut to access the data attribute directly.) However, this doesn't work when the array item has been updated in an input, since jsviews try to trigger setProperty on a simple property. Results in changes not reflected to the original array.

**Comment by BorisMoore** [comment]
Closing "After V1.0" issues for now - to reopen as appropriate.
