### ISSUE TITLE
Add support for '}' characters within string literals in data-link expressions

### ISSUE THREAD

**Issue by govis** [BorisMoore/jsviews#55]
Hi Boris,

Trying to upgrade from the previous version I encountered the following issue.

I use data-link converter functions as follows:
data-link="{:~formatterFunc('Showing {0} items in {1} folder', ItemCount, FolderName)}"

Where formatterFunc helper is something similar to String.Format in .NET.

With your latest bits I get an error during a call to $.link("#container", data)
“Unterminated string constant”. 

If I remove the {0} and {1} from the string, it works fine. Also if was working with the last version of jsViews.

Error is coming form 
function linkViews( node, parent, nextNode, depth, data, context, prevNode, index ) { .. }, which seems to be parsing the string literals.

It is turning out  to be a great library so far, keep up the great work.

Thanks.

**Comment by BorisMoore** [comment]
Closing "After V1.0" issues for now - to reopen as appropriate.
