### ISSUE TITLE
cancel and validation on data linked edit form

### ISSUE THREAD

**Issue by bzuidgeest** [BorisMoore/jsviews#57]
This is more an advice question instead of an issue. I created an table and use the link function to render the rows. Then when an edit button is clicked I change a row to an edit template. I took this technique from the accordion example and it works perfectly. 

In the row there is also an cancel button when in edit mode. However because of the datalinking I no longer have the original object and thus I cannot change back to the original values. 

I have several options here. I can request the original object from the server or I can use one of the clone scripts to store a copy of data on the view object. Both these options have their disadvantages. Is there a better way of implementing a "cancel" functionality? Maybe there is an option for delayed binding with an hook or something....

**Comment by BorisMoore** [comment]
Closing "After V1.0" issues for now - to reopen as appropriate.
