### ISSUE TITLE
Add support for inline data-linking for attributes - attr="{^{...}}", and server rendering using same template.

### ISSUE THREAD

**Issue by kaste** [BorisMoore/jsviews#69]
Right now I don't know where to post this, so I put it here.

I used jsviews and jsrender several times during alpha and pre-beta, but I always wonder about the data-from, -getfrom and from now on data-link design. I usually think in terms of static and 'live' templates, or 'static' vs. live views. And a couple of times I already had my jsrender-templates set up, and wanted to convert them to 'live' views on a later iteration. Because only on a second or third iteration of a page it feels right to say: Ok, I want that section to update automatically; I want these new messages or friend requests to 'fly in'. But then it's a pain to switch from a jsrender template to a jsview 'view'.

So, why do we need this `data-link` stuff?

```html
<input data-link="{:lastName:} title{:~infoSummary(firstName, lastName, address.city, cars.quantity)}" />
<p data-link="css-background-color{:roleColor}">
<span data-link="lastName"></span>
```

Why can't we have the exact same and one-and-only syntax for our templates, but later decide if we want to link them to data, that eventually changes, or if we just want to render exactly that data-object?

```html
<input value="{{: lastName}}" title="{{: ~infoSummary(firstName, lastName, address.city, cars.entity) )}}" />
<span class="{{: ~isManager(#data) ? 'vip' : 'nip'}}">{{: lastName}}</span>
```

I don't like the `data-link="css-background-color{:roleColor}"` at all, it feels like inlining javascript or css and I usually don't do this. And btw these data-link strings tend to get very big very fast. It's like writing this old style-stuff before we used css-classes.

**Comment by BorisMoore** [comment]
Closing "After V1.0" issues for now - to reopen as appropriate.
