### ISSUE TITLE
Using addviews function in jsviews

### ISSUE THREAD

**Issue by bzuidgeest** [BorisMoore/jsviews#94]
I need some advise using the addviews function in jsviews. 

I have the following html

```html

<div class="section rounded span6">
	
    <div class="section-header single-line">
		<i class="icon-calendar icon-medium icon-single pull-left"></i>
		<h2 class="span2 pull-left">Notities</h2>
        <span class="pull-right"><input id="showAllNotes" type="checkbox" onchange="loadNotes()"/>Toon alle notities van deze student</span>
	</div>
		
    <div id="divNotes"></div>
    <div class="article-footer">
        <button id="newNote" class="btn btn-primary" >Nieuwe notitie</button>
    </div>
	
</div> 	

```

Items are retrieved from a webservice and are linked to divNotes using this statement.

```javascript

$.link.templateNoteRow(data, "#divNotes");

```

This is the template

```html
<script id="templateNoteRow" type="text/x-jsrender">
    <div class="article no-padding" >
 		<div class="article-header" style="height:100%;">
			<p class="inline extra-margin right span2"><i class="icon-calendar"></i>{{toJavascriptDate:Created}}
            <p class="inline extra-margin right span2"><i class="icon-calendar"></i>{{:Category}}</p>
            
            <button class="btn noteEdit">Bewerken</button>
            <button class="btn btn-danger noteDelete">Verwijderen</button>
            
            <br />
                       
            <p>{{:~substring(Text, 200)}}...</p>
			            
		</div>
	</div>
</script>
```

So far so good. Now I want to add another view to this using addviews when a click on the newNote button is clicked. Since I do not like data duplication. I want to use the jsviews addViews function for this directly and not adding items to an observed array. I create my event for the newnote button as below

```javascript

$('#newNote').on('click', function () {
        if (selectedNoteView != null)
            unselectNote();

        var data = {
            Id: 0,
            StudentId: studentId,
            DossierId: plusDossierId,
            Category: '-',
            Text: '',
            DossierType: 1,
            Created: toMicrosoftDate(Date.now())
        };

 //attempt 1
        $.view(this).views["_2"].addViews($.view(this).views["_2"].views.length, [data], "templateNoteRow");

        //attempt2
        //$.view($(".noteEdit")).parent.addViews($.view($(".noteEdit")).parent.views.length, [data], "templateNoteEditRow");
});
```

attemp2 can be used as long as the webservice returns at least one item. It finds one item and it use the addviews function on its parent. attemp1 also works when the webservice returned an empty array (which is linked) and there are no items rendered to the screen. However it requires me nowing the index of the view "collection/root". There is more linking going on in the page so in this case it's _2, but that is not very usable and might change. 

I tried using $.view($("#divNotes")) but that does not give met the same object as  $.view(this).views["_2"]. 

What is the proper way, if any to get the root view in an reusable way? What statement should I use in $.view(????)

Hope I made the question clear. If not, do say so.

**Comment by BorisMoore** [comment]
It looks like this is trying to use View APIs to respond to data changes. The primary paradigm supported by JsViews is declarative data-driven views, using `{^{...}}` and `data-link="..."` syntax. views.addViews is a lower-level API used to implement the above declarative scenario, but I would not recommend using it in parallel with declarative approaches - since the two can get out of sync. Closing this issues, as not being a fully supported or desired scenario.
